### PR TITLE
loose escaping, ban undefined, change char for objects

### LINKED ISSUE #10: preserve type for undefined
`undefined` values now parse back as string, it potentially could break something:

``` js
var obj = { foo: undefined }
assert.deepEqual(parse(stringify(obj)), obj) // fail: { foo: 'undefined' } expected to be { foo: undefined }
```

I want to fix this as part of 3.0 release since it is could be breaking for someone.

### LINKED ISSUE #12: Consider improving the notation syntax
Currently urlon uses `_` to define objects.

``` javascript
URLON.parse('_table_achievement_column=instance&ascending:true')

// Output:  {"table":{"achievement":{"column":"instance","ascending":true}}} 
```

Underscores are not so uncommon in url params and could be either confusing at first or causing trouble with legacy urls. Maybe there is a way of improving this with an alternate notation pattern.

The first thing that popped into my head was:

``` javascript
URLON.parse('table.achievement.column=instance&ascending:true')
URLON.parse('table.achievement={column:instance,ascending:true')}
```

That's just phantasy though and hasn't been further evaluated in regards to technical limitations etc.

### PR DESCRIPTION
**Pull request by Guria**
preparing next major release

fixes #10, fixes #12 

cc @vjeux

### CODE REVIEW

**Comment by Guria** [comment]
will split in several commits for better history

**Comment by Guria** [comment]
runkit notebook to play with:
https://runkit.com/guria/5a09a6bcd653430011415441

**Comment by vjeux** [comment]
Works for me :)

**Comment by Guria** [comment]
merged

**Pull request merged**
